language: objective-c

before_install:
- launchctl list
- brew install reattach-to-user-namespace
- reattach-to-user-namespace launchctl list

script: 
- reattach-to-user-namespace xctool -project BButtonDemo.xcodeproj -scheme BButtonDemo -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO clean build test
- reattach-to-user-namespace xctool -project BButtonDemo.xcodeproj -scheme BButtonDemoTests -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO clean build run-tests -freshSimulator -freshInstall

after_script:
- launchctl list
- reattach-to-user-namespace launchctl list
- ls -lt ~/Library/Application\ Support/iPhone\ Simulator/7.0.3/Applications/
- find ~/Library/Application\ Support/iPhone\ Simulator/ -name 'BButton*.app'
