language: objective-c

before_install:
- uptime
- launchctl list
- launchctl list com.apple.quicklook
- brew install reattach-to-user-namespace
- reattach-to-user-namespace launchctl list
- reattach-to-user-namespace launchctl list com.apple.quicklook

script: 
- reattach-to-user-namespace xctool -project BButtonDemo.xcodeproj -scheme BButtonDemo -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO clean build test
- reattach-to-user-namespace xctool -project BButtonDemo.xcodeproj -scheme BButtonDemoTests -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO clean build run-tests -freshSimulator -freshInstall

after_script:
- ps auxwww
- launchctl list
- reattach-to-user-namespace launchctl list
- ls -lt ~/Library/Application\ Support/iPhone\ Simulator/7.0.3/Applications/
- find ~/Library/Application\ Support/iPhone\ Simulator/ -name 'BButton*.app'
- cat ~/Library/Application\ Support/iPhone\ Simulator/7.0.3/var/run/launchd_bootstrap.plist
- cat ~/Library/Logs/iOS\ Simulator/7.0.3/system.log
- cat /var/log/system.log
